// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Powerball_Ticket_Generator.Models;

namespace PowerBall.Migrations
{
    [DbContext(typeof(LotteryContext))]
    partial class LotteryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Powerball_Ticket_Generator.Models.Genre", b =>
                {
                    b.Property<string>("GenreId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = "L1",
                            Name = "Lottery Genre 1"
                        },
                        new
                        {
                            GenreId = "L2",
                            Name = "Lottery Genre 2"
                        });
                });

            modelBuilder.Entity("Powerball_Ticket_Generator.Models.Lottery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerballNumbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lottary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            FullName = "John Doe",
                            Gender = "Male",
                            Location = "New York",
                            PowerballNumbers = "1 2 3 4 5 PB: 6"
                        },
                        new
                        {
                            Id = 2,
                            Age = 28,
                            FullName = "Jane Smith",
                            Gender = "Female",
                            Location = "Los Angeles",
                            PowerballNumbers = "7 8 9 10 11 PB: 12"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
